### ISSUE TITLE
Uncaught TypeError: Cannot read property 'postMessage' of undefined

### ISSUE THREAD

**Issue by littlesalt** [duyduong/interactive_webview#5] opened 2019-01-24 07:12 UTC
When click button test and send message from js to flutter,the error is display.
my js code is here:
<!doctype html>
<html>
<head>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
</head>
<body>
	<button id="zf" onclick="testsend()">test</button><br/><br/>
  <script>

    const nativeCommunicator =
 typeof webkit !== 'undefined' ? webkit.messageHandlers.native : window.native;

    function test(text) {
      console.log(`received from native ${text}`);
      const data = [{name: "Hello"}, 1, true, "from", "WebView!!!"];
      nativeCommunicator.postMessage('ok？');
    }
 function testsend() {
      nativeCommunicator.postMessage('hello');
    }

  </script>
</body>
</html>`

**Comment by duyduong** [comment] 2019-03-11 09:46
Can u reproduce on latest version?

**Comment by duyduong** [comment] 2019-09-10 09:24
@littlesalt Plugin has updated to latest. I will close the issue, re-open it if the issue is still existing

**Closed as completed by duyduong** 2019-09-10 09:24 UTC
